### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [jenny-leung/jammming#1]
Good Job. The code was clean and easy to follow. No major errors were detected. I would like to leave a tip on making comments in react here: http://wesbos.com/react-jsx-comments/

**Comment by jenny-leung** [comment]
Thank you very much for reviewing. I have experience in JavaScript, but I'm new to React. I did this project by following the instructions and some steps are confusing. If I were to start this project from scratch, do you have any good examples and articles that could help me learn and figure out the code myself. I think some good articles and tips would help me understand React more.

**Comment by mp1pro** [comment]
The best one stop for documentation on react is https://reactjs.org/
For more info refer to react advisors at codecademy

Marvin Parke
Web Developer
cel phone: 3058963657
Github: https://github.com/mp1pro
Linkedin: https://www.linkedin.com/in/marvinparke

**Comment by jenny-leung** [comment]
Thank for you advise.
